version: "3.8"
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 3308:3306 # local:container
    volumes:
      - ./Banco/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database-volume:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "MYSQL_PWD=12345 mysqladmin ping -h localhost -P 3306 -u root",
        ]
      interval: 2s
      timeout: 20s
      retries: 10
  sgp-es2-api:
    image: enzobonf/sgp-es2-api:latest
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./Backend/.env.production
    volumes:
      - ./Backend:/app
      - /app/node_modules
      - ./Backend/firebase.credentials.json:/app/../firebase.credentials.json
      - ./Backend/package.json:/app/../package.json
    links:
      - db
  sgp-es2-frontend:
    image: enzobonf/sgp-es2-web:latest
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - 80:80 # local:container
    volumes:
      - ./Frontend:/app
volumes:
  database-volume:
